# Generated by Django 4.1 on 2023-10-16 16:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('PORTIFOLIO', 'Portifolio'), ('PROJETOS', 'Projetos'), ('CLT', 'clt'), ('COMUNIDADE', 'Comunidade')], default='', max_length=100)),
                ('description', models.TextField()),
                ('path', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('published', models.BooleanField(default=False)),
                ('date_photography', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
