# Generated by Django 4.1 on 2023-10-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
